version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cpms-postgres
    environment:
      POSTGRES_DB: cpms
      POSTGRES_USER: cpmsuser
      POSTGRES_PASSWORD: StrongP@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cpms-api:
    build:
      context: .
      dockerfile: CPMS.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__MartenDb=Host=postgres;Database=cpms;Username=cpmsuser;Password=Password123
    depends_on:
      - postgres

  cpms-proxy:
    build:
      context: .
      dockerfile: CPMS.Proxy/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - CpmsApi__BaseUrl=http://cpms-api:8080
    depends_on:
      - cpms-api

  cpms-frontend:
    build:
      context: .
      dockerfile: CPMS.Frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - cpms-api
      - cpms-proxy

volumes:
  postgres-data: